- name: Install OpenObserve
  hosts: all
  vars:
    openobserve_dir: /etc/bbkane/openobserve/v0.6.2
  tasks:
    - name: Create OpenObserve directory
      become: true
      ansible.builtin.file:
        path: "{{ openobserve_dir }}"
        state: directory
        mode: '0755'

    - name: Install binary
      become: true
      ansible.builtin.unarchive:
        src: ~/Downloads/openobserve-v0.6.2-linux-amd64.tar.gz
        dest: "{{ openobserve_dir }}"

    - name: Copy env file template
      become: true
      notify: Restart service
      ansible.builtin.template:
        src: ./templates/openobserve.env
        dest: "{{ openobserve_dir }}/openobserve.env"
        owner: root
        group: root
        mode: '0600'

    - name: Copy unit file template
      become: true
      notify: Restart service
      ansible.builtin.template:
        src: ./templates/openobserve.service
        dest: "/etc/systemd/system/openobserve.service"
        owner: root
        group: root
        mode: '0600'

    - name: Enable service
      become: true
      ansible.builtin.systemd_service:
        enabled: true
        state: started
        name: openobserve.service

  handlers:
    - name: Restart service
      become: true
      ansible.builtin.systemd_service:
        enabled: true
        state: restarted
        daemon_reload: true
        name: openobserve.service
